kind: Deployment
apiVersion: apps/v1
metadata:
  name: data-api
  labels:
    app: data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
      - name: data-api-pods

        image: ssbendre1/customerinfo:backend

        ports:
        - containerPort: 3000

        resources:
          limits:
            memory: "256M"
            cpu: "0.25"